### ISSUE TITLE
details plural vs detail singular 

### ISSUE THREAD

**Issue by voltagex** [NRWLDev/fastapi-problem#25]
It looks like the RFC specifies a "detail" attribute, but fastapi-problem creates a "details" attribute - do I have this backwards?

**Comment by EdgyEdgemond** [comment]
You do indeed have it right, I'll see if I can support both as a means of maintaining backwards compat, or if it seems too fiddly will make a breaking change to switch it to the correct format.

**Comment by EdgyEdgemond** [comment]
Thanks for catching that, fixed in https://github.com/NRWLDev/fastapi-problem/releases/tag/v0.9.0
